server:
  port: 8081

spring:
  security:
    user:
      name: root
      password: 123456
      roles: admin

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weblog?severTimezone=GMT%2B8@useSLL=true&allowMultiQueries=true
    username: root
    password: 123456
  application:
    name: blog-post
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos地址
    service-registry:
      auto-registration:
        enabled: true

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

mybatis:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com.weblog.persistence.mapper: DEBUG