server:
  port: 8081

spring:
  security:
    user:
      name: root
      password: 123456
      roles: admin

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weblog?severTimezone=GMT%2B8@useSLL=true&allowMultiQueries=true
    username: root
    password: 123456

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

  mail:
    host: smtp.163.com
    username: meidochanVKX@163.com  # 最后记得把这里的信息抹掉
    password: JRVCXKASBRFGRJWG      # 最后记得把这里的信息抹掉
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: false
            required: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com.weblog.persistence.mapper: DEBUG