server:
  port: 8080
spring:
  security:
    user:
      name: root
      password: 123456
      roles: admin

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weblog?severTimezone=GMT%2B8@useSLL=true
    username: root
    password: 123456

  servlet:
    multipart:
      max-file-size: 536870912  # 512MB
      max-request-size: 536870912
      location: ./

  mvc:
    static-path-pattern: /static/** # 这个接口不在API文档中, 只用来做重定向

  web:
    resources:
      static-locations:
        - file:./src/
        # 这四个是默认配置
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

  application:
    name: blog-blog

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos地址
    service-registry:
      auto-registration:
        enabled: true


mybatis:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com.weblog.persistence.mapper: DEBUG